#!/usr/bin/env bash
set -euo pipefail

ROOT=${ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}
ROOT_LABEL=${ROOT_LABEL:-.}
OUT=${OUT:-${ROOT}/docs/ai-native/module-inventory-report.md}

if command -v rg >/dev/null 2>&1 && rg --version >/dev/null 2>&1; then
  SEARCH=(rg --ignore-case --no-heading --line-number --hidden --glob '!vendor/**' --glob '!third_party/**' --glob '!**/.git/**' --glob '!docs/ai-native/module-inventory-report.md')
else
  SEARCH=(grep -REIn --exclude-dir=vendor --exclude-dir=third_party --exclude-dir=.git --exclude=module-inventory-report.md)
fi

count_matches() {
  local pattern=$1
  "${SEARCH[@]}" -e "${pattern}" "${ROOT}" 2>/dev/null | wc -l | tr -d ' '
}

top_files() {
  local pattern=$1
  "${SEARCH[@]}" -e "${pattern}" "${ROOT}" 2>/dev/null \
    | sed "s#${ROOT}/##" \
    | awk -F: '{count[$1]++} END {for (file in count) print count[file], file}' \
    | sort -rn \
    | head -12 \
    | awk '{n=$1; $1=""; sub(/^ /,""); printf "- `%s`: %s\n", $0, n}'
}

emit_section() {
  local title=$1
  local pattern=$2
  local decision=$3

  {
    printf '\n## %s\n\n' "${title}"
    printf 'Pattern: `%s`\n\n' "${pattern}"
    printf 'Match count: `%s`\n\n' "$(count_matches "${pattern}")"
    printf 'Initial decision: %s\n\n' "${decision}"
    printf 'Top files:\n\n'
    top_files "${pattern}" || true
  } >>"${OUT}"
}

mkdir -p "$(dirname "${OUT}")"

cat >"${OUT}" <<EOF
# Module Inventory Report

Generated by: \`hack/ai-native/module-inventory.sh\`

Repository root: \`${ROOT_LABEL}\`

This is a first-pass static inventory. It is not a removal list. Use it to decide what to keep, replace, defer, or separate behind internal interfaces.
EOF

emit_section "License And Entitlement Candidates" 'license|licence|edition|entitlement|subscription' "Replace through an internal entitlement interface after runtime behavior is understood."
emit_section "Application And Appstore Surfaces" 'appstore|applicationrelease|applicationversion|application\.kubesphere\.io|app repo|app template' "Defer removal; separate after core resource-management smoke tests are stable."
emit_section "Extension And Museum Surfaces" 'extension|museum|installplan|repository|jsbundle|reverseproxy' "Keep disabled in dev values; decide later whether to become an internal plugin system."
emit_section "Telemetry Support Cloud Defaults" 'telemetry|support|kubesphere cloud|cloud|about|official' "Disable outbound defaults first; replace with internal observability and product metadata."
emit_section "IAM Auth RBAC Surfaces" 'iam|auth|rbac|rolebinding|globalrole|workspace role|jwt|oauth|login' "Keep as core platform; must become the authorization base for Agent actions."
emit_section "K8s Resource Management Surfaces" 'kapis/resources|resource/v1|workload|deployment|statefulset|daemonset|pod|service|ingress|persistentvolume|storageclass|event' "Keep as core platform and reuse for read-only Agent inventory."
emit_section "Terminal Kubeconfig Exec Surfaces" 'terminal|kubeconfig|exec|shell|pty|websocket' "Keep but gate strongly for human and Agent use."
emit_section "Agent Candidate Names" 'agent|ai|llm|copilot|assistant|operationplan|audit' "Use as namespace discovery; introduce explicit Agent APIs instead of overloading generic names."

cat >>"${OUT}" <<'EOF'

## Next Manual Review

- Review high-count files for false positives.
- Pick exact backend API groups and frontend routes that belong to appstore/extension separation.
- Locate all entitlement/license behavior before changing runtime decisions.
- Define first Agent read-only inventory endpoint using existing resource stores.
EOF

echo "wrote ${OUT}"
